# Data Storage
# If use-mysql is false, the plugin will use flatfile
use-mysql: false

# turn this on when using the same SQL db across multiple servers, doesn't apply to flatfile too
live-sync: false

# range in block of beacon
# a 256 block radius would affect a 257x257 square area area with the beacon in the center block
# reinforce is the multiplier of durability
# reinforce adds durability to blocks in the range of a beacon if materials from chests place on the beacon pyramid are available
# you are setting the maximum value for this
beacon_tiers:
  tier1:
    range: 40
    reinforce: 2
  tier2:
    range: 60
    reinforce: 3
  tier3:
    range: 80
    reinforce: 4
  tier4:
    range: 100
    reinforce: 5

# add/remove as needed
# if there is no max durability the plugin will use the global default durability
# 'BLOCK: <default durability>,<max reinforce durability>'
# setting both to 1 would result in vanilla behavior
default_durability: 1
default_max_durability: 10

block_durabilities:
  - 'OBSIDIAN: 5'
  - 'STONE: 2'
  - 'STONE_BRICKS: 3'
  - 'BEACON: 1, 1'
  - 'ANDESITE: 5, 20'
  - 'WOOD_LOG: 5'

interact_protect:
  # list of blocks that will allow interaction if their durability reaches 1
  unlockable:
    - 'CHEST'
    - 'LEVER'
  # false: whitelist, so only blocks listed below will be protected
  # true: blacklist, so blocks listed below will not be protected
  blacklist: true
  list:
    - 'STONE_BUTTON'
    - 'HEAVY_WEIGHTED_PRESSURE_PLATE'
    - 'STONE_PRESSURE_PLATE'
    - 'WOOD_PLANKS'

# list of moving entities to watch for
# no need to add stationary entities like end crystals
explosive_entity_protect:
  - 'PRIMED_TNT'
  - 'MINECART_TNT'
  - 'CREEPER'
  - 'FIREBALL'
  - 'SMALL_FIREBALL'

# how long to keep players in reinforce mode (seconds) if they don't cancel it themselves
reinforce_delay: 5

# blocks can be reinforced with items other than themselves and in custom amounts
# a positive number will reinforce by x amount, and a negative number needs x to reinforce
# so OAK_PLANKS:2 will reinforce twice and STICKS:-4 will use 4 sticks for 1 reinforce
# 'MATERIAL: <MATERIAL>:<amt>, <MATERIAL>:<amt>'
custom_reinforce:
  - 'CHEST:CHEST:2,WOOD_PLANKS:-4,STICK:-8,WOOD_LOG:2'
  - 'ACACIA_DOOR,BIRCH_DOOR,DARK_OAK_DOOR,JUNGLE_DOOR,OAK_DOOR,SPRUCE_DOOR:WOOD_PLANKS:2'

# create custom groups to use - WOOD_LOG for all the log types
alternates:
  - 'WOOD_LOG:ACACIA_LOG,BIRCH_LOG,DARK_OAK_LOG,JUNGLE_LOG,OAK_LOG,SPRUCE_LOG'
  - 'WOOD_PLANKS:ACACIA_PLANKS,BIRCH_PLANKS,DARK_OAK_PLANKS,JUNGLE_PLANKS,OAK_PLANKS,SPRUCE_PLANKS'
