# Data Storage
# If use-mysql is false, the plugin will use flatfile
use-mysql: false

# turn this on when using the same SQL db across multiple servers, doesn't apply to flatfile too
live-sync: false

# range in block of beacon
# a 256 block radius would affect a 257x257 square area area with the beacon in the center block
# reinforce is the multiplier of durability
# reinforce adds durability to blocks in the range of a beacon if materials from chests place on the beacon pyramid are available
# you are setting the maximum value for this
beacon_tiers:
  tier1:
    range: 40
    reinforce: 2
  tier2:
    range: 60
    reinforce: 3
  tier3:
    range: 80
    reinforce: 4
  tier4:
    range: 100
    reinforce: 5

# add/remove as needed
# if there is no max durability the plugin will use the global default durability
# 'BLOCK: <default durability>,<max reinforce durability>'
# setting both to 1 would result in vanilla behavior
default_durability: 1
default_max_durability: 10

block_durabilities:
  - 'OBSIDIAN: 5'
  - 'STONE: 2'
  - 'STONE_BRICKS: 3'
  - 'BEACON: 1, 1'
  - 'ANDESITE: 5, 20'

# which blocks beacons should protect from interaction
# also set true if the block can be used when durability is 1
# helpful so you don't have to break a chest and put contents on the ground to steal from it
# 'MATERIAL: true/false' also leave blank for false but to still protect from interaction
interact_protect:
  - 'CHEST: true'
  - 'LEVER: true'
  - 'STONE_BUTTON: true'
  - 'HEAVY_WEIGHTED_PRESSURE_PLATE'