# Data Storage
# If use-mysql is false, the plugin will use flatfile
use-mysql: false

# turn this on when using the same SQL db across multiple servers, doesn't apply to flatfile too
live-sync: false

# range in block of beacon
# a 256 block radius would affect a 257x257 square area area with the beacon in the center block
beacon_tiers:
  tier1: 40
  tier2: 60
  tier3: 80
  tier4: 100

#add/remove as needed
# if there is no max durability the plugin will use the global default durability
# 'BLOCK: <default durability>,(max reinforcable durability)
# setting both to 1 would result in vanilla behavior
default_durability: 1

block_durabilities:
  - 'OBSIDIAN: 5'
  - 'STONE: 2'
  - 'STONE_BRICKS: 3'
  - 'BEACON: 1, 1'