name: BeaconProtect
version: 0.1
author: LemonPickles
api-version: 1.14
main: net.lemonpickles.BeaconProtect.BeaconProtect
website: lemonpickles.net
commands:
  beaconprotect:
    description: Main command for BeaconProtect
    usage: /beaconprotect <arguments>
    aliases: [bp]
  group:
    description: BeaconProtect command for managing groups
    usage: /group arguments